version: '3'

services:
  front:
        build: .
        environment:
            - CHOKIDAR_USEPOLLING='true'
        command: 'npx vite'
        ports:
            - "5173:5173"
        volumes:
            - ".:/app"